name: BattleRoyale
version: 1.0-SNAPSHOT
main: ltotj.minecraft.battleroyale.Main
api-version: 1.16
depend: [NBTAPI]
commands:
  battleroyale:
    usage: "/battleroyale help"

permissions:
  op:
    default: op
  player:
    default: true
