name: BattleRoyale
version: ${project.version}
main: ltotj.minecraft.battleroyale.Main
api-version: 1.16
depend: [NBTAPI]
commands:
  battleroyale:
    usage: "/battleroyale help"
    aliases: [bat, btr, battle]

permissions:
  op:
    default: op
  player:
    default: true
