main: battleroyale.Main
name: BattleRoyale
version: 1.0.0
api-version: 1.16
depend: [NBTAPI]
commands:
  battleroyale:
    usage: "/battleroyale help"

permissions:
  op:
    default: op
  player:
    default: true